services:
  - type: web
    name: new-decors
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python migrate.py
    startCommand: gunicorn ecommerce_complet:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
